FROM node:16-alpine

EXPOSE 80

WORKDIR /var/www

COPY dist/apps/backend /var/www

ENV NODE_ENV production
ENV PORT 80

RUN yarn config set registry "https://registry.npm.taobao.org" && \
 yarn install && \
 yarn cache clean

CMD node main.js
