import { NgModule } from '@angular/core';

import { DefinitionsComponent } from './definitions.component';
import { DefinitionUtilsModule } from './definition-utils';
import {
  ButtonDefinitionModule,
  CalendarDefinitionModule,
  ChatDefinitionModule,
  CardDefinitionModule,
  CheckboxDefinitionModule,
  InputDefinitionModule,
  ProgressBarDefinitionModule,
  RadioDefinitionModule,
  SelectDefinitionModule,
  SpaceDefinitionModule,
  TextDefinitionModule,
  LinkDefinitionModule,
  TabsDefinitionModule,
  StepperDefinitionModule,
  LineChartDefinitionModule,
  BarChartDefinitionModule,
  PieChartDefinitionModule,
  MultipleAxisChartDefinitionModule,
  MultipleBarChartDefinitionModule,
  DoughnutChartDefinitionModule,
  BubbleMapDefinitionModule,
  MapDefinitionModule,
  SmartTableDefinitionModule,
  TableDefinitionModule,
  ButtonLinkDefinitionModule,
  HeadingDefinitionModule,
  ImageDefinitionModule,
  MenuDefinitionModule,
  IconDefinitionModule,
  AccordionDefinitionModule,
  DatepickerDefinitionModule,
  HeaderDefinitionModule,
  SidebarDefinitionModule,
  SidebarToggleDefinitionModule,
  IframeDefinitionModule,
  DividerDefinitionModule,
  ListDefinitionModule
} from './components-definitions';
import {
  ContactsDefinitionModule,
  LoginDefinitionModule,
  RegisterDefinitionModule,
  UsersDefinitionModule,
  OrdersDefinitionModule,
  StatisticsDefinitionModule,
  TasksDefinitionModule,
  Login2DefinitionModule,
  Register2DefinitionModule,
  Login3DefinitionModule,
  ProfileDefinitionModule,
  StatusCardDefinitionModule,
  StatusChartDefinitionModule,
  StatusChart2DefinitionModule,
  MultiColumnFormDefinitionModule
} from './widget-definitions';

const DEFINITIONS = [DefinitionsComponent];

@NgModule({
  imports: [
    DefinitionUtilsModule,
    CardDefinitionModule,
    ButtonDefinitionModule,
    ButtonLinkDefinitionModule,
    InputDefinitionModule,
    TextDefinitionModule,
    SpaceDefinitionModule,
    CheckboxDefinitionModule,
    SelectDefinitionModule,
    RadioDefinitionModule,
    ProgressBarDefinitionModule,
    CalendarDefinitionModule,
    ChatDefinitionModule,
    LinkDefinitionModule,
    TabsDefinitionModule,
    StepperDefinitionModule,
    LineChartDefinitionModule,
    BarChartDefinitionModule,
    PieChartDefinitionModule,
    MultipleAxisChartDefinitionModule,
    MultipleBarChartDefinitionModule,
    DoughnutChartDefinitionModule,
    BubbleMapDefinitionModule,
    MapDefinitionModule,
    TableDefinitionModule,
    SmartTableDefinitionModule,
    HeadingDefinitionModule,
    ImageDefinitionModule,
    MenuDefinitionModule,
    IconDefinitionModule,
    AccordionDefinitionModule,
    ListDefinitionModule,
    HeaderDefinitionModule,
    DatepickerDefinitionModule,
    SidebarDefinitionModule,
    SidebarToggleDefinitionModule,
    LoginDefinitionModule,
    RegisterDefinitionModule,
    ContactsDefinitionModule,
    UsersDefinitionModule,
    OrdersDefinitionModule,
    StatisticsDefinitionModule,
    TasksDefinitionModule,
    Login2DefinitionModule,
    Register2DefinitionModule,
    Login3DefinitionModule,
    ProfileDefinitionModule,
    StatusCardDefinitionModule,
    StatusChartDefinitionModule,
    StatusChart2DefinitionModule,
    MultiColumnFormDefinitionModule,
    IframeDefinitionModule,
    DividerDefinitionModule
  ],
  exports: [...DEFINITIONS],
  declarations: [...DEFINITIONS]
})
export class DefinitionsModule {
}
