apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubesphere
    component: $APP_NAME-$BRANCH_NAME
    tier: backend
  name: $APP_NAME-$BRANCH_NAME
  namespace: nginx-project
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: kubesphere
      component: $APP_NAME-$BRANCH_NAME
      tier: backend
  template:
    metadata:
      labels:
        app: kubesphere
        component: $APP_NAME-$BRANCH_NAME
        tier: backend
    spec:
      volumes:
        - name: env-$APP_NAME-$BRANCH_NAME-$BUILD_NUMBER
          secret:
            secretName: $APP_NAME-$BRANCH_NAME-env
            defaultMode: 420
        - name: volume-data-$APP_NAME-$BRANCH_NAME-$BUILD_NUMBER
          persistentVolumeClaim:
            claimName: $APP_NAME
      containers:
        - name: $APP_NAME
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:$BRANCH_NAME-$BUILD_NUMBER
          ports:
            - name: http-80
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: env-$APP_NAME-$BRANCH_NAME-$BUILD_NUMBER
              readOnly: true
              mountPath: /var/www/.env
              subPath: .env
            - name: volume-data-$APP_NAME-$BRANCH_NAME-$BUILD_NUMBER
              readOnly: false
              mountPath: /data
          env:
            - name: CACHE_IGNORE
              value: js|html
            - name: CACHE_PUBLIC_EXPIRATION
              value: 3d
          readinessProbe:
            httpGet:
              path: /api
              port: 80
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: aliyun-registry
