# curl 'http://127.0.0.1:4200/api/upload/excel'
#  -H 'Connection: keep-alive'
#  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36'
#  -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryDNIBcKjfBBFHwgLj'
#  -H 'Accept: */*'
#  -H 'Origin: http://127.0.0.1:4200'
#  -H 'Sec-Fetch-Site: same-origin'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Referer: http://127.0.0.1:4200/'
#  -H 'Accept-Language: zh,en-US;q=0.9,en;q=0.8'
#  --compressed


POST http://127.0.0.1:3001/api/upload/excel
Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
Accept: */*
Origin: http://127.0.0.1:4200
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://127.0.0.1:4200/
Accept-Language: zh,en-US;q=0.9,en;q=0.8
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryDNIBcKjfBBFHwgLj

###

POST http://localhost:3002/api/queryStr
Content-Type: application/json

{
  "key": "211:16:e3a409bfcc7eef50849837880fca7e8bcb6042b5bdaf6e831ffb4141a4e7c08c"
}

###
# curl -X POST "http://localhost:3002/api/queryStr" -H  "accept: */*" -H  "Content-Type: application/json" -d "{\"name\":\"string\",\"age\":0,\"breed\":\"string\"}"
POST http://localhost:3002/api/queryStr
accept: */*
Content-Type: application/json

{
  "name": "string",
  "age": 0,
  "breed": "string"
}

###



POST http://localhost:3001/api/upload/excel

--null


< C:\Users\zwx973267\Desktop\dcs.xlsx
--null--

###

